### ISSUE TITLE
Unable to compile on Ubuntu 14.04 after pull request #55

### ISSUE THREAD

**Issue by Georift** [enkore/j4-dmenu-desktop#56]
I was getting the following error while trying to compile from master:

```
[ 50%] Built target catch
[ 56%] Building CXX object CMakeFiles/j4-dmenu-desktop.dir/src/main.cc.o
In file included from /home/tim/j4-dmenu-desktop/src/main.cc:2:0:
/home/tim/j4-dmenu-desktop/src/Main.hh: In member function ‘int Main::main(int, char**)’:
/home/tim/j4-dmenu-desktop/src/Main.hh:60:43: error: no matching function for call to ‘std::locale::locale(std::string&)’
         std::locale locale(suffixes.locale);
                                           ^
/home/tim/j4-dmenu-desktop/src/Main.hh:60:43: note: candidates are:
In file included from /usr/include/c++/4.8/bits/ios_base.h:41:0,
                 from /usr/include/c++/4.8/ios:42,
                 from /usr/include/c++/4.8/istream:38,
                 from /usr/include/c++/4.8/fstream:38,
                 from /home/tim/j4-dmenu-desktop/src/Main.hh:1,
                 from /home/tim/j4-dmenu-desktop/src/main.cc:2:
/usr/include/c++/4.8/bits/locale_classes.h:311:5: note: std::locale::locale(std::locale::_Impl*)
     locale(_Impl*) throw();
     ^
/usr/include/c++/4.8/bits/locale_classes.h:311:5: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘std::locale::_Impl*’
/usr/include/c++/4.8/bits/locale_classes.h:178:7: note: template<class _Facet> std::locale::locale(const std::locale&, _Facet*)
       locale(const locale& __other, _Facet* __f);
       ^
/usr/include/c++/4.8/bits/locale_classes.h:178:7: note:   template argument deduction/substitution failed:
In file included from /home/tim/j4-dmenu-desktop/src/main.cc:2:0:
/home/tim/j4-dmenu-desktop/src/Main.hh:60:43: note:   cannot convert ‘((Main*)this)->Main::suffixes.LocaleSuffixes::locale’ (type ‘std::string {aka std::basic_string<char>}’) to type ‘const std::locale&’
         std::locale locale(suffixes.locale);
                                           ^
In file included from /usr/include/c++/4.8/bits/ios_base.h:41:0,
                 from /usr/include/c++/4.8/ios:42,
                 from /usr/include/c++/4.8/istream:38,
                 from /usr/include/c++/4.8/fstream:38,
                 from /home/tim/j4-dmenu-desktop/src/Main.hh:1,
                 from /home/tim/j4-dmenu-desktop/src/main.cc:2:
/usr/include/c++/4.8/bits/locale_classes.h:164:5: note: std::locale::locale(const std::locale&, const std::locale&, std::locale::category)
     locale(const locale& __base, const locale& __add, category __cat);
     ^
/usr/include/c++/4.8/bits/locale_classes.h:164:5: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/4.8/bits/locale_classes.h:151:5: note: std::locale::locale(const std::locale&, const char*, std::locale::category)
     locale(const locale& __base, const char* __s, category __cat);
     ^
/usr/include/c++/4.8/bits/locale_classes.h:151:5: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/4.8/bits/locale_classes.h:137:5: note: std::locale::locale(const char*)
     locale(const char* __s);
     ^
/usr/include/c++/4.8/bits/locale_classes.h:137:5: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const char*’
/usr/include/c++/4.8/bits/locale_classes.h:126:5: note: std::locale::locale(const std::locale&)
     locale(const locale& __other) throw();
     ^
/usr/include/c++/4.8/bits/locale_classes.h:126:5: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const std::locale&’
/usr/include/c++/4.8/bits/locale_classes.h:117:5: note: std::locale::locale()
     locale() throw();
     ^
/usr/include/c++/4.8/bits/locale_classes.h:117:5: note:   candidate expects 0 arguments, 1 provided
In file included from /home/tim/j4-dmenu-desktop/src/main.cc:2:0:
/home/tim/j4-dmenu-desktop/src/Main.hh: In member function ‘void Main::collect_files()’:
/home/tim/j4-dmenu-desktop/src/Main.hh:187:33: warning: ignoring return value of ‘char* getcwd(char*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
         getcwd(original_wd, 384);
                                 ^
/home/tim/j4-dmenu-desktop/src/Main.hh:195:32: warning: ignoring return value of ‘int chdir(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
             chdir(path.c_str());
                                ^
/home/tim/j4-dmenu-desktop/src/Main.hh:204:27: warning: ignoring return value of ‘int chdir(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
         chdir(original_wd);
                           ^
In file included from /home/tim/j4-dmenu-desktop/src/Main.hh:15:0,
                 from /home/tim/j4-dmenu-desktop/src/main.cc:2:
/home/tim/j4-dmenu-desktop/src/Application.hh: In member function ‘bool Application::read(const char*, char**, size_t*)’:
/home/tim/j4-dmenu-desktop/src/Application.hh:94:29: warning: ignoring return value of ‘char* getcwd(char*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
             getcwd(pwd, 100);
                             ^
In file included from /home/tim/j4-dmenu-desktop/src/Main.hh:14:0,
                 from /home/tim/j4-dmenu-desktop/src/main.cc:2:
/home/tim/j4-dmenu-desktop/src/Dmenu.hh: In member function ‘void Dmenu::write(const string&)’:
/home/tim/j4-dmenu-desktop/src/Dmenu.hh:19:61: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
         ::write(this->outpipe[1], what.c_str(), what.size());
                                                             ^
/home/tim/j4-dmenu-desktop/src/Dmenu.hh:20:43: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
         ::write(this->outpipe[1], "\n", 1);
                                           ^
In file included from /home/tim/j4-dmenu-desktop/src/main.cc:2:0:
/home/tim/j4-dmenu-desktop/src/Main.hh: In member function ‘std::string Main::get_command()’:
/home/tim/j4-dmenu-desktop/src/Main.hh:247:37: warning: ignoring return value of ‘int chdir(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
             chdir(app->path.c_str());
                                     ^
make[2]: *** [CMakeFiles/j4-dmenu-desktop.dir/src/main.cc.o] Error 1
make[1]: *** [CMakeFiles/j4-dmenu-desktop.dir/all] Error 2
make: *** [all] Error 2
```

I'm running GCC version 4.84. I was however able to build when I checked out r2.14.

**Comment by enkore** [comment]
Does patching line 60 in Main.hh from `std::locale locale(suffixes.locale);` to `std::locale locale(suffixes.locale.c_str());` fix this?

**Comment by Georift** [comment]
Yes, that looks to have fixed it.

**Comment by glubsy** [comment]
Thanks, had the same issue on Linux Mint 17.3 (ubuntu 14.04 based). :+1:

**Comment by doubledodge** [comment]
Another thank you from me for this fix to  Main.hh - I came across the same build error on Debian 7 wheezy (I was forced to build an old wheezy based VM in order to install the rather outdated .deb images for EPICS from NSLS2) but I can't survive in i3-wm without the trusty j4-dmenu-desktop so many thanks for this wonderful bit of code for those mice averse tilling window manager users such as me.  :)
